---
kind: pipeline
type: docker
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:5.10.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: install-node-14
  image: livingdocs/node:14
  commands: ["npm install"]

- name: test-node-14
  image: livingdocs/node:14
  commands: ["npm run test"]
  depends_on: [install-node-14]

- name: install-node-16
  image: livingdocs/node:16
  commands: ["npm install"]

- name: test-node-16
  image: livingdocs/node:16
  commands: ["npm run test"]
  depends_on: [install-node-16]

- name: publish
  image: livingdocs/semantic-release:v1.2.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]

---
kind: signature
hmac: 02e1a6b0de55e1aaa3f1c1290f8684cd7191e98c156646578199b7d7a5029702

...
