---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:5.10.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: install
  image: livingdocs/node:12.3
  commands: ["npm install"]

- name: test-node-12
  image: livingdocs/node:12.3
  commands: ["npm run test"]
  depends_on: [install]

- name: test-node-14
  image: livingdocs/node:14.3
  commands: ["npm run test"]
  depends_on: [install]

- name: publish
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]

---
kind: signature
hmac: 0466f46a5e2904b562ae10ae950b7883622a595297f975a69934e112ebb64a42

...
