---
kind: pipeline
type: docker
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:5.10.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: install-node-14
  image: livingdocs/node:14
  commands: ["npm install"]

- name: test-node-14
  image: livingdocs/node:14
  commands: ["npm run test"]
  depends_on: [install-node-14]

- name: install-node-16
  image: livingdocs/node:16
  commands: ["npm install"]

- name: test-node-16
  image: livingdocs/node:16
  commands: ["npm run test"]
  depends_on: [install-node-16]

- name: publish
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]

---
kind: signature
hmac: 8bb7b5727ce4b4bdbd21f46dabfa8d0fc63c7a6868a45288d1c3257095af5f65

...
